server:
  port: ${PORT:8080}

  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: pigeon_kart
    hibernate:
      ddl-auto: none